/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    Button: typeof import('primevue/button')['default']
    CaptureArea: typeof import('./src/components/CaptureArea.vue')['default']
    Card: typeof import('primevue/card')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    MeterGroup: typeof import('primevue/metergroup')['default']
    Popover: typeof import('primevue/popover')['default']
    SharingPanel: typeof import('./src/components/SharingPanel.vue')['default']
    SpriteCard: typeof import('./src/components/SpriteCard.vue')['default']
    SpriteFiltersBar: typeof import('./src/components/SpriteFiltersBar.vue')['default']
    SpritePopover: typeof import('./src/components/SpritePopover.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
    ToastNotification: typeof import('./src/components/ToastNotification.vue')['default']
  }
}
